# Generated by Django 3.0.4 on 2020-04-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to=core.models.custom_upload_to)),
                ('memoria', models.IntegerField(blank=True, null=True)),
                ('kernel', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
