# Generated by Django 3.0.4 on 2020-05-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chmaquina', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Archivo',
        ),
        migrations.AlterModelOptions(
            name='archivo',
            options={'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
    ]
