# Generated by Django 3.0.4 on 2020-05-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chmaquina', '0002_auto_20200507_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivo',
            options={},
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='imagen',
        ),
        migrations.AddField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivosCh/'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='kernel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivo',
            name='memoria',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
