# Generated by Django 3.0.4 on 2020-05-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chmaquina', '0003_auto_20200507_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='bodega/'),
        ),
    ]
