# Generated by Django 2.2.1 on 2020-05-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chmaquina', '0005_kernel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kernel',
            old_name='kernel',
            new_name='Kkernel',
        ),
        migrations.RenameField(
            model_name='kernel',
            old_name='memoria',
            new_name='Kmemoria',
        ),
    ]
