# Generated by Django 2.2.1 on 2020-05-16 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chmaquina', '0006_auto_20200516_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kernel',
            old_name='Kkernel',
            new_name='kerK',
        ),
        migrations.RenameField(
            model_name='kernel',
            old_name='Kmemoria',
            new_name='memoK',
        ),
    ]
