# Generated by Django 2.2.1 on 2020-05-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chmaquina', '0008_lea'),
    ]

    operations = [
        migrations.CreateModel(
            name='HUMMMM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoK', models.IntegerField(blank=True, null=True)),
                ('kerK', models.IntegerField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='bodega/')),
                ('memoria', models.IntegerField(blank=True, default=100, null=True)),
                ('kernel', models.IntegerField(blank=True, default=9, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='archivo',
            name='kernel',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='memoria',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
