# Generated by Django 2.2.1 on 2020-05-18 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chmaquina', '0009_auto_20200518_1742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HUMMMM',
        ),
    ]
