# Generated by Django 2.2.1 on 2020-05-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chmaquina', '0010_delete_hummmm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lea',
            name='lea',
            field=models.TextField(blank=True, default=1, null=True),
        ),
    ]
