# Generated by Django 2.2.1 on 2020-05-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chmaquina', '0011_auto_20200518_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='hmmmm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='bodega/')),
                ('memoria', models.IntegerField(blank=True, default=100, null=True)),
                ('kernel', models.IntegerField(blank=True, default=9, null=True)),
            ],
        ),
    ]
