# Generated by Django 2.2.1 on 2020-05-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chmaquina', '0012_hmmmm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hmmmm',
        ),
    ]
