# Generated by Django 2.2.1 on 2020-05-19 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chmaquina', '0014_auto_20200518_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='kernel',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='memoria',
        ),
    ]
