# Generated by Django 2.2.1 on 2020-05-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chmaquina', '0015_auto_20200518_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='bodega/'),
        ),
    ]
