# Generated by Django 2.2.1 on 2020-05-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chmaquina', '0016_archivo_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='kernel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivo',
            name='memoria',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
