# Generated by Django 2.2.1 on 2020-05-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chmaquina', '0017_auto_20200518_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lea',
            name='lea',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
