# Generated by Django 2.2.1 on 2020-05-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chmaquina', '0018_auto_20200518_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lea',
            old_name='lea',
            new_name='Lea',
        ),
    ]
