# Generated by Django 2.2.1 on 2020-05-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chmaquina', '0019_auto_20200519_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lea',
            name='Lea',
        ),
        migrations.AddField(
            model_name='lea',
            name='leaLea',
            field=models.TextField(blank=True, null=True),
        ),
    ]
