# Generated by Django 2.2.1 on 2020-05-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chmaquina', '0020_auto_20200519_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='lea',
            field=models.TextField(blank=True, null=True),
        ),
    ]
