# Generated by Django 2.2.1 on 2020-05-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chmaquina', '0023_auto_20200519_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lea',
            old_name='leaLea',
            new_name='lea',
        ),
    ]
