# Generated by Django 2.2.1 on 2020-05-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chmaquina', '0024_auto_20200519_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lea',
            name='lea',
            field=models.TextField(blank=True, null=True),
        ),
    ]
